version: '3.9'

services:
  mysql:
    image: mysql
    restart: always
    env_file:
      - .env.local
    ports:
      - "3307:3306"
    networks:
      - magazord
  php:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8123:8123"
    env_file:
      - .env.local
    volumes:
      - ./src:/app
    depends_on:
      - mysql
    entrypoint: "php -S 0.0.0.0:8123"
    working_dir: /app
    networks:
      - magazord
networks:
  magazord:
    name: magazord