version: '3'

services:
  mysql:
    image: mysql
    restart: always
    env_file:
      - .env.local
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env.local